# Generated by Django 2.1.2 on 2018-10-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('patient',)},
        ),
    ]
